version: '3'

services:
  web:
    container_name: item-manager-nginx
    image: nginx:latest
    ports:
      - "8001:8001"
    volumes:
      - .:/item-manager
      - ./build/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    container_name: item-manager-php
    build:
      context: ./build
      dockerfile: app.docker
    working_dir: /item-manager
    volumes:
      - .:/item-manager      
  mysql:
    container_name: item-manager-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'item_manager'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ../data/mysql:/var/lib/mysql
    ports:
      - '3307:3306' 
    
  redis:
    image: redis
    container_name: item-manager-redis
    volumes:
      - ../data/redis:/var/lib/redis
    ports:
      - "6379:6379"

  redisui:
    image: rediscommander/redis-commander:latest
    container_name: item-manager-redisui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"